name: Develop - build and push image
on:
  push:
    branches:
      - master
env:
  ENVIRONMENT: develop

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish
    runs-on: [ self-hosted ]
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup NX workspace SHAs
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn

      - name: Login to npm
        run: echo "${{ secrets.NPM_AUTH }}" >> .npmrc

      - name: Compute actually changed files
        run: |
          git cherry-pick --abort || true
          git cherry-pick `git log  $NX_BASE..$NX_HEAD --grep='\[skip ci\]' --grep '[Mm]erge' --invert-grep  --pretty="%H" | tr '\n' ' '`
          NX_AFFECTED_FILES=`git diff --name-only | sort | uniq | tr '\n' ','`
          git cherry-pick --abort

      - name: 'Build affected apps'
        run:  yarn nx affected --target=ci --parallel=1 --files="$NX_AFFECTED_FILES"
